<a href="https://colab.research.google.com/github/alimoorreza/CS167-fall24-notes/blob/main/Day20_MLP_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS167: Day20

## MLP using PyTorch

### CS167: Machine Learning, Fall 2024


📆 [Course Schedule](https://analytics.drake.edu/~reza/teaching/cs167_fall24/cs167_schedule.html) | 📜 [Syllabus](https://analytics.drake.edu/~reza/teaching/cs167_fall24/cs167_syllabus_fall24.pdf)


In [1]:
# import torch library
import torch
import numpy as np
import torch.nn as nn


# Creating Linear Layers using PyTorch

## **Let's build a linear layer**

In [2]:
torch.manual_seed(2)                    # for reproducibility
# construction of a linear layer
num_of_neurons_input_layer      = 2
num_of_neurons_output_layer     = 3

input_linear_layer1              = nn.Linear(num_of_neurons_input_layer, num_of_neurons_output_layer)  # linear transformation module (input=2, output=3)
input_linear_layer2              = nn.Linear(256, 4)  # linear transformation module (input=256, output=4)


##**Inspecting the weights of a linear layer**

In [3]:
# Print the weights of the linear layer
print(f'Weights: \n{input_linear_layer1.weight.data}')

# Print the biases of the linear layer (if they exist)
print(f'Biases: \n{input_linear_layer1.bias.data}')

Weights: 
tensor([[ 0.1622, -0.1683],
        [ 0.1939, -0.0361],
        [ 0.3021,  0.1683]])
Biases: 
tensor([-0.0813, -0.5717,  0.1614])


## **Let's generate a random input for our linear layer and plug it into our layer**

In [7]:
# Step 1: let's generate 1 random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples     = 1
random_input          = torch.randn(number_of_samples, 2)
print(f'input numbers: \n{random_input.numpy()}\n')


# Step 2: apply forward pass through the network
output                = input_linear_layer1(random_input)
print(f'output layer value: \n{output.data.numpy()}\n')


input numbers: 
[[ 0.39229682 -0.22356401]]

output layer value: 
[[ 0.01998059 -0.48752502  0.24230729]]



In [8]:
# Step 1: let's generate 3 random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples     = 3
random_input          = torch.randn(number_of_samples, 2)
print(f'input numbers: \n{random_input.numpy()}\n')


# Step 2: apply forward pass through the network
output                = input_linear_layer1(random_input)
print(f'output layer value: \n{output.data.numpy()}\n')


input numbers: 
[[ 0.39229682 -0.22356401]
 [-0.31950027 -1.2050371 ]
 [ 1.0444635  -0.6332277 ]]

output layer value: 
[[ 0.01998059 -0.48752502  0.24230729]
 [ 0.06968039 -0.5901005  -0.13792734]
 [ 0.19469965 -0.34626803  0.3703416 ]]



##**Group Exercise#1**
Create a new Linear layer with the following structure:

> The first layer has 3 input nodes and 6 output nodes.


In [ ]:
# your code here
# ...


##**Group Exercise#2**

> Apply a tensor through your linear layer now.

> Change the value in torch.manual_seed(0) to something else, generate new inputs, and pass the tensor through your linear layer again.

> Observe the the output values.

In [ ]:
# your code here.
# ...



## **Let's add an activation function such as *ReLu(), tanh(), or sigmoid()* after your linear layer and run the experiment again to see how it changes the outputs.**

In [11]:
# construction of a linear layer
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)
num_of_neurons_input_layer      = 2
num_of_neurons_output_layer     = 3

input_linear_layer              = nn.Linear(num_of_neurons_input_layer, num_of_neurons_output_layer)  # linear transformation module (input=2, output=3)
sigmoid_activation              = nn.Sigmoid()
tanh_activation                 = nn.Tanh()
relu_activation                 = nn.ReLU()



##**Using Sigmoid activation function**

In [12]:
# Step 1: let's generate some random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

number_of_samples     = 1
random_X              = torch.randn(number_of_samples, num_of_neurons_input_layer)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# Step 2: apply forward pass through the network
output                    = input_linear_layer(random_X)
output_after_activation   = sigmoid_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('Sigmoid activation value: ')
print(output_after_activation.data.numpy())


input numbers:
[[ 0.39229682 -0.22356401]]
output layer value: 
[[ 0.01998059 -0.48752502  0.24230729]]
Sigmoid activation value: 
[[0.504995  0.3804768 0.5602822]]


##**Using Tanh activation function**

In [13]:
# Step 1: let's generate some random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

number_of_samples     = 1
random_X              = torch.randn(number_of_samples, num_of_neurons_input_layer)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# Step 2: apply forward pass through the network
output                    = input_linear_layer(random_X)
output_after_activation   = tanh_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('Tanh() activation value: ')
print(output_after_activation.data.numpy())


input numbers:
[[ 0.39229682 -0.22356401]]
output layer value: 
[[ 0.01998059 -0.48752502  0.24230729]]
Tanh() activation value: 
[[ 0.01997794 -0.45224985  0.2376739 ]]


##**Using ReLU activation function**

In [14]:
# Step 1: let's generate some random samples of (x1, x2) for the above linear network
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

number_of_samples     = 1
random_X              = torch.randn(number_of_samples, num_of_neurons_input_layer)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# Step 2: apply forward pass through the network
output                    = input_linear_layer(random_X)
output_after_activation   = relu_activation(output)
print('output layer value: ')
print(output.data.numpy())
print('ReLU() activation value: ')
print(output_after_activation.data.numpy())


input numbers:
[[ 0.39229682 -0.22356401]]
output layer value: 
[[ 0.01998059 -0.48752502  0.24230729]]
ReLU() activation value: 
[[0.01998059 0.         0.24230729]]


##**Group Exercise#3**

> Experiment with different activation functions like sigmoid, tanh, and relu, and then pass a tensor through the linear layer you created for Group Exercises #1 and #2.

> Change the value in torch.manual_seed(2) to something else, generate new inputs, and pass the tensor through your linear layer again.

> Take a look at the output values and make sure they match what you were expecting!

In [ ]:
# your code here.
# ...


## **Let's build the simple 1-hidden layer feedforward neural network from the lecture slides!**

<div>
<img src="https://analytics.drake.edu/~reza/teaching/cs167_fall24/notes/images/mlp_toy_examle_wo_weights.png" width=400/>
</div>


In [15]:
# let's make the simple 1-Hidden layer feedforwrd neural network from the lecture slides
torch.manual_seed(2) # for reproducibility (you will get the same random number every time you run this cell)

# construction
num_of_neurons_input_layer      = 2
num_of_neurons_1st_hidden_layer = 3
num_of_neurons_output_layer     = 1

'''
# Alternatively, you could hardcode the values for the number of neurons directly, without using any variables such as 'num_of_neurons_input_layer ' or 'num_of_neurons_1st_hidden_layer'
input_linear_layer              = nn.Linear(2, 3)
output_linear_layer             = nn.Linear(3, 1) # linear transformation module (input=3, output=1)
'''


input_linear_layer              = nn.Linear(num_of_neurons_input_layer, num_of_neurons_1st_hidden_layer)  # linear transformation module (input=2, output=3)
relu_activation_h1              = nn.ReLU()
output_linear_layer             = nn.Linear(num_of_neurons_1st_hidden_layer, num_of_neurons_output_layer) # linear transformation module (input=3, output=1)



## **We can apply a tensor through the Linear layers now**

In [18]:
# let's generate 2 random samples of (x1, x2) for the above linear network
torch.manual_seed(2)                                    # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples               = 1
random_X = torch.randn(number_of_samples, 2)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# apply forward pass through the network
output = input_linear_layer(random_X)
output = relu_activation(output)
print('1st-hidden layer feature map shape: ', output.shape)
output = output_linear_layer(output)
print('Output layer feature map shape: ', output.shape)


input numbers:
[[ 0.39229682 -0.22356401]]
1st-hidden layer feature map shape:  torch.Size([1, 3])
Output layer feature map shape:  torch.Size([1, 1])


## **nn.Sequential()__ module:**
You can use PyTorch's nn.Sequential module to build a network composed of multiple linear layers arranged sequentially.

In [25]:
my_simple_network = nn.Sequential(
    nn.Linear(2, 3),
    nn.ReLU(),
    nn.Linear(3, 1)
)

In [28]:
# let's generate 2 random samples of (x1, x2) for the above linear network
torch.manual_seed(2)                                    # for reproducibility (you will get the same random number every time you run this cell)
number_of_samples               = 1
random_X = torch.randn(number_of_samples, 2)             # you could imagine that these are pairs of (x1, x2) as shown in the above table
print('input numbers:')
print(random_X.numpy())


# apply forward pass through the network
output = my_simple_network(random_X)
print('Output: ', output.data)
print('Output layer feature map shape: ', output.shape)


input numbers:
[[ 0.39229682 -0.22356401]]
Output:  tensor([[0.2181]])
Output layer feature map shape:  torch.Size([1, 1])


#**Group Exercise#4**
Let's create three Linear layers and connect them in sequence to build an MLP with the following structure:

> The first layer has 2 input nodes and 3 output nodes.

> The second layer takes 3 input nodes and outputs 6 nodes.

> The final layer connects 6 input nodes to 2 output nodes.

In [29]:
# your code here
# ...


## **Group Exercise#5**
> Apply a tensor through your MLP now.

In [ ]:
# your code here
# ...


You could apply an input to individual layer as follows:

In [ ]:
input = torch.randn(1, 2)
print(f'input: {input.numpy()}')
output = my_simple_network[0](input)
print(f'{output.data}')
print(f'shape: {output.shape}')

# Try next layer



# Try next next layer

